### PR TITLE
Fix memcached use

### PR DESCRIPTION
**Pull request by samfrench**

### CODE REVIEW

**Comment by samfrench** [comment]
@dazoakley, can you review and merge this for us please?

This should fix the issue reported here:

http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoDiscovery.AddingToYourClientLibrary.html

> Each node in the list is represented by a hostname|ip-address|port group, and each node is delimited by a space.

Thanks,
Ettore and Sam.

**Comment by dazoakley** [comment]
Looks good to me :+1:

**Comment by dazoakley** [comment]
Also, thanks for the fix :)

**Comment by samfrench** [comment]
@dazoakley, thank you for merging.

Ettore and Sam.

**Pull request merged**
